In [30]:
import datetime

In [31]:
df = pd.to_datetime([1528902000,
1528905304,
1528905078,
1528905305,
1528905306,
1528905311,
1528903200,
1528905312,
1528901400,
1528905315,
1528901580,
1528905321,
1528901160,
1528905323,
1528905298,
1528905325,
1528903800,
1528905326,
1528901100,
1528905330,
1528904340,
1528905297,
1528905332,
1528905333,
1528905334,
1528901760,
1528905300,
1528905336,
1528905338,
1528905339,
1528902900,
1528905340,
1528905342,
1528902960,
1528905347,
1528905349,
1528905350,
1528905351,
1528905352,
1528905353,
1528905357,
1528903860,
1528905182,
1528905299,
1528905359,
1528905099,
1528905360,
1528905361,
1528904100,
1528901220,
1528905366,
1528902540,
1528905368,
1528905370,
1528905371,
1528905373,
1528905377,
1528905379,
1528905380,
1528902660,
1528905381,
1528905382,
1528905387,
1528905600,
1528903560,
1528905388,
1528905389,
1528905390,
1528905391,
1528905392,
1528902600,
1528905397,
1528905398,
1528905399,
1528905400,
1528905401,
1528905404,
1528905405,
1528905407,
1528903500,
1528905408,
1528905409,
1528905413,
1528905414,
1528905415,
1528905416,
1528905417,
1528905418,
1528905419,
1528905420,
1528905421,
1528905423,
1528905424,
1528905425,
1528905429,
1528902840,
1528905430,
1528905431,
1528905432,
1528905433,
1528905434,
1528905439,
1528905442,
1528905443,
1528905444,
1528901880,
1528905445,
1528905450,
1528901820,
1528905451,
1528905453,
1528905454,
1528905455,
1528905456,
1528905458,
1528905459,
1528905461,
1528905464,
1528905465,
1528905466,
1528905467,
1528905468,
1528905469,
1528905470,
1528905435,
1528905476,
1528905477,
1528905363,
1528905478,
1528905479,
1528905480,
1528905481,
1528905482,
1528905485,
1528905486,
1528905487,
1528905488,
1528905495,
1528905496,
1528905498,
1528905499,
1528905500,
1528905402,
1528905501,
1528905503,
1528905506,
1528905507,
1528905508,
1528905510,
1528905240,
1528901040,
1528905511,
1528905516,
1528905517,
1528901700,
1528905520,
1528905521,
1528905526,
1528905527,
1528905530,
1528905531,
1528905536,
1528905537,
1528905538,
1528905539,
1528905541,
1528905546,
1528905000,
1528905547,
1528905549,
1528905550,
1528905551,
1528905555,
1528900860,
1528905556,
1528905557,
1528905558,
1528905559,
1528905560,
1528905561,
1528905563,
1528905564,
1528905565,
1528905567,
1528905568,
1528905573,
1528905575,
1528905577,
1528905582,
1528905583,
1528905584,
1528905585,
1528905587,
1528905589,
1528905592,
1528905593,
1528905594,
1528905596,
1528905597,
1528904640,
1528905599,
1528905605,
1528905642,
1528905610,
1528905646,
1528905619,
1528903440,
1528905629,
1528905630,
1528905631,
1528905632,
1528905633,
1528905472]
)

In [32]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

print(df)

DatetimeIndex([   '1970-01-01 00:00:01.528902',
               '1970-01-01 00:00:01.528905304',
               '1970-01-01 00:00:01.528905078',
               '1970-01-01 00:00:01.528905305',
               '1970-01-01 00:00:01.528905306',
               '1970-01-01 00:00:01.528905311',
               '1970-01-01 00:00:01.528903200',
               '1970-01-01 00:00:01.528905312',
               '1970-01-01 00:00:01.528901400',
               '1970-01-01 00:00:01.528905315',
               ...
               '1970-01-01 00:00:01.528905610',
               '1970-01-01 00:00:01.528905646',
               '1970-01-01 00:00:01.528905619',
               '1970-01-01 00:00:01.528903440',
               '1970-01-01 00:00:01.528905629',
               '1970-01-01 00:00:01.528905630',
               '1970-01-01 00:00:01.528905631',
               '1970-01-01 00:00:01.528905632',
               '1970-01-01 00:00:01.528905633',
               '1970-01-01 00:00:01.528905472'],
              dtype='datetime64[ns]', length=213, freq=None)

In [ ]:
# inverted 
stamps = pd.date_range("1970-06-30", periods=4, freq="D")